services:
  - type: web
    name: nft-garant-bot
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN
      - key: ADMIN_ID
        value: YOUR_ADMIN_ID
